name: MY FIRST DOCKER GITHUB ACTION

on:
  push:
    branches:
       - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build docker images
        run: docker build -t demo .

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.MY-DOCKER-HUB-ACCESS-TOKEN }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.dckr_pat_9oMq5DThU14SiNWDBgaYL4M7MTM }}
        run: 
          docker login -u $DOCKER_USERNAME --p $DOCKER_ACCESS_TOKEN
        
      - name: Build and tag Docker image
        run: 
          docker build -t skopiskopa:latest -f Dockerfile .
          docker tag skopiskopa:latest skopiskopa:${{ github.sha }}
